services:
  backend:
    image: ghcr.io/loudbooks/codebook-backend:latest
    container_name: codebook-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/codebook
      - SPRING_DATA_MONGODB_DATABASE=codebook
      - S3_ACCESS_KEY_ID=minioadmin
      - S3_SECRET_ACCESS_KEY=minioadmin
      - S3_BUCKET=codebook
      - S3_ENDPOINT=http://minio:9000
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - codebook-network

  frontend:
    image: ghcr.io/loudbooks/codebook-frontend:latest
    container_name: codebook-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - TITLE=${TITLE}
      - DESCRIPTION=${DESCRIPTION}
      - DISABLE_NEW=${DISABLE_NEW}
      - FAVICON_URL=${FAVICON_URL}
      - MAX_PAYLOAD_SIZE=${MAX_PAYLOAD_SIZE}
      - BACKEND_PORT=${BACKEND_PORT}
    depends_on:
      - backend
    networks:
      - codebook-network
    pull_policy: always

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: codebook
    volumes:
      - mongo-data:/data/db
    networks:
      - codebook-network
    pull_policy: always
    
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: always
    command: server /data/db
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data/db
    networks:
      codebook-network:
        aliases:
            - codebook.minio
    pull_policy: always
    healthcheck:                                                                                                                                               
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]                                                                                   
      interval: 2s                                                                                                                                             
      timeout: 2s                                                                                                                                              
      retries: 5 
      
volumes:
  mongo-data:
  minio-data:

networks:
  codebook-network:
    driver: bridge
