name: Build and Publish Docker Images

on:
  workflow_dispatch:
  push:
    paths:
      - frontend/**
      - backend/**
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        component: [frontend, backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Commit Hash
        id: get_commit_hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set Docker Tags
        id: set_tags
        run: |
          if [ "${{ github.ref_name }}" == "master" ]; then
            echo "tag=latest" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "dev" ]; then
            echo "tag=dev" >> $GITHUB_ENV
          else
            echo "Unknown branch: ${{ github.ref_name }}"
            exit 1
          fi

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.component }}
          file: ./${{ matrix.component }}/Dockerfile
          build-args: |
            COMMIT_HASH=${{ env.hash }}
          push: true
          tags: |
            ghcr.io/loudbooks/codebook-${{ matrix.component }}:${{ env.tag }}
            ghcr.io/loudbooks/codebook-${{ matrix.component }}:${{ env.hash }}
